In [1]:
%pip install pyldpc


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: C:\Users\victo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [1]:
import numpy as np
from pyldpc import make_ldpc, decode, get_message
import random

In [7]:
n = 6000  # Nombre total de bits du code
d_v = 2  # Degré des noeuds variables
d_c = 3  # Degré des noeuds de parité

# Génération de la matrice de parité H et de la matrice de génération G du code LDPC
H, G = make_ldpc(n, d_v, d_c)

# Affichage du nombre de bits codés
n, number_of_bits = G.shape
print("Number of base bits:", number_of_bits)

# Initialisation des listes pour stocker les taux d'erreur
errors = []

initial_message = []

for loop in range(number_of_bits):
  initial_message.append(random.randint(0,1))
print("Message initial : ", initial_message)

n_trials = 25  # number of transmissions with different noise
V = np.tile(initial_message, (n_trials, 1)).T  # stack v in columns

encoded_matrix = decode(H, V, 20)  # Décodage du message
print("Message avec code d'erreur LDPC : ", encoded_matrix)

altered_encoded_matrix = encoded_matrix
alteration_pourcent = 15

for array in range(int(altered_encoded_matrix.size / n_trials)):
  if(array % (100/alteration_pourcent) == 0):
    if (altered_encoded_matrix[array][0] == 0):
      altered_encoded_matrix[array][0] = 1
    else:
      altered_encoded_matrix[array][0] = 0

print("Message avec code d'erreur LDPC altéré à ", alteration_pourcent, "%: ", altered_encoded_matrix)

errorpourcent = 0.0

for i in range(n_trials):
  final_message = get_message(G, altered_encoded_matrix[:, i]) # Récupération du message décodé

print("Message final : ", final_message)

for error in range(final_message.size):
  if(final_message[error] != initial_message[error]):
    errorpourcent += 1

errorpourcent /= final_message.size

print("Pourcentage d'intégrité des données : ", 100 - errorpourcent*100, "%")

Number of base bits: 201
Message initial :  [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1]
Message avec code d'erreur LDPC :  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Message avec code d'erreur LDPC altéré à  5 %:  [[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Message final :  [0 0 0 0 0 0